version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - checkout
      - run:
          name: Instalando dependencias de pilas
          command: make iniciar
      - run:
          name: Ejecutando test
          command: make test
  deploy:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
        - checkout
        - run: make iniciar
        - run: echo "Instalando wine ..."
        - run: sudo dpkg --add-architecture i386 && sudo apt update
        - run: sudo apt install wine wine32 wine64 libwine libwine:i386 fonts-wine
        - run: make binarios
        - run: echo "Instalando go y ghr ..."
        - run: sudo apt-get install golang
        - run: GOPATH="/tmp/go" go get github.com/tcnksm/ghr
        - run: /tmp/go/bin/ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` binarios/
    release:
      tag: /v[0-9]+(\.[0-9]+)*/
  deploy_a_surge:
    machine: true
    steps:
        - checkout
        - run: make iniciar
        - run:
            name: "Subiendo archivos a surge..."
            command: make deploy_a_surge
        - run: circleci step halt
    release:
      tag: /v[0-9]+(\.[0-9]+)*/
  finalizar:
    docker:
      - image: circleci/node:8.9.4-stretch-browsers
    steps:
      - run: echo "Terminado"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          filters:
            tags:
              only: /^v.*/
      - deploy_a_surge
      - finalizar:
          requires:
            - deploy_a_surge
            - deploy
