version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.13.0-stretch-browsers
    steps:
      - checkout
      - run:
          name: Instalando dependencias de pilas
          command: make iniciar
      - run:
          name: Ejecutando test
          command: make test
  deploy:
    machine:
        enabled: true
    steps:
        - checkout
        - run: make iniciar
        - run: go get github.com/tcnksm/ghr
        - run: echo "Instalando wine ..."
        - run: sudo dpkg --add-architecture i386
        - run: sudo add-apt-repository -y ppa:ubuntu-wine/ppa
        - run: sudo apt-get update
        - run: echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
        - run: sudo apt-get install -y wine
        - run: make binarios
        - run: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` binarios/
    release:
      tag: /v[0-9]+(\.[0-9]+)*/
  deploy_a_surge:
    machine:
        enabled: true
    steps:
        - checkout
        - run: make iniciar
        - run: 
            command: make deploy_a_surge 
            no_output_timeout: 3600
    release:
      tag: /v[0-9]+(\.[0-9]+)*/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
      - deploy_a_surge:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
